version: 0.2
phases:
  install:
    commands:
      #install node version 16
      - curl -fsSL https://deb.nodesource.com/setup_16.x | -E bash -
      - apt-get install -y nodejs

  pre_build:
    commands:
      # install dependencies
      - cd my-app
      - npm install

  build:
    commands:
      #test
      - npm test
      #build
      - npm run build

artifacts:
  files: -"**/*"
  base-directory: my-app
  discard-paths: yes
