version: 0.2
phases:
  install:
    commands:
      #install node version 16
      - curl -fsSL https://deb.nodesource.com/setup_16.x | -E bash -
      - apt-get install -y nodejs
      - npm install

  pre_build:
    commands:
      #install dependencies
      # - npm i
      cd my-app

  build:
    commands:
      #test
      - npm test
      #build
      - npm build

artifacts:
  files: -"**/*"
  discard-paths: no
